# training data: 405
 # testing data 72
Traceback (most recent call last):
  File "/home/hypatia/6D-DAAD/Edge-Grasp-Network/train.py", line 63, in <module>
    main(args)
  File "/home/hypatia/6D-DAAD/Edge-Grasp-Network/train.py", line 60, in main
    edge_grasper.train_test_save(tr_loader, tst_loader,tr_epoch=args.epoch,test_interval=args.test_interval,
  File "/home/hypatia/6D-DAAD/Edge-Grasp-Network/models/edge_grasper.py", line 61, in train_test_save
    run_acc += accu
UnboundLocalError: local variable 'run_acc' referenced before assignment